name: Continuos Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    name: continuos-integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        witch:
          node-version: 18.x
      - uses: expo/expo-github-action@v8
        witch:
          expo-version: 49.x
      - run: npm install
      - run: npm run test